angular.module('josephsItemsJSON', [])

.service('$josephsItemsJSON', function () {
    var _items = {

        "Items": {
            "ItemResponse": [
              {
                  "ItemCode": "10122",
                  "Description": "PureCare Invigorate",
                  "Price": 19.9500,
                  "CommissionableVolume": 20,
                  "BusinessVolume": 20,
                  "Other1Price": "0.0000",
                  "Other2Price": "0.0000",
                  "Other3Price": "0.0000",
                  "Other4Price": "0.0000",
                  "Other5Price": "0.0000",
                  "Other6Price": "0.0000",
                  "Other7Price": "0.0000",
                  "Other8Price": "0.0000",
                  "Other9Price": "0.0000",
                  "Other10Price": "0.0000",
                  "Category": "Health & Wellness",
                  "CategoryID": "26",
                  "TinyPicture": "1001C.jpg",
                  "SmallPicture": "1001B.jpg",
                  "LargePicture": "1001A.jpg",
                  "ShortDetail": "",
                  "ShortDetail2": "",
                  "ShortDetail3": "",
                  "ShortDetail4": "",
                  "LongDetail": "This is a wonderful product. ",
                  "LongDetail2": "Purecare has created a wonderfully invigorating product. ",
                  "LongDetail3": "",
                  "LongDetail4": "",
                  "InventoryStatus": "Available",
                  "StockLevel": "-4",
                  "AvailableStockLevel": "-247",
                  "MaxAllowedOnOrder": "1000000000",
                  "Field1": "",
                  "Field2": "",
                  "Field3": "",
                  "Field4": "Prepared Foods",
                  "Field5": "",
                  "Field6": "",
                  "Field7": "",
                  "Field8": "",
                  "Field9": "",
                  "Field10": "",
                  "OtherCheck1": "true",
                  "OtherCheck2": "false",
                  "OtherCheck3": "false",
                  "OtherCheck4": "false",
                  "OtherCheck5": "false",
                  "IsVirtual": "true",
                  "AllowOnAutoOrder": "true",
                  "IsGroupMaster": "false",
                  "GroupDescription": "",
                  "GroupMembersDescription": "",
                  "IsDynamicKitMaster": "true",
                  "KitMembers": {
                      "KitMemberResponse": [
                        {
                            "Description": "Cannister",
                            "KitMemberItems": {
                                "KitMemberItemResponse": [
                                  {
                                      "ItemCode": "Burn-2272",
                                      "Description": "Red/Black Burn Band Med",
                                      "InventoryStatus": "OutOfStock"
                                  },
                                  {
                                      "ItemCode": "Burn-2289",
                                      "Description": "Red/Black Burn Band Large",
                                      "InventoryStatus": "OutOfStock"
                                  },
                                  {
                                      "ItemCode": "Burn-2296",
                                      "Description": "Red/Black Burn Band XL",
                                      "InventoryStatus": "OutOfStock"
                                  }
                                ]
                            }
                        },
                        {
                            "Description": "Cannister",
                            "KitMemberItems": {
                                "KitMemberItemResponse": [
                                  {
                                      "ItemCode": "Burn-2272",
                                      "Description": "Red/Black Burn Band Med",
                                      "InventoryStatus": "OutOfStock"
                                  },
                                  {
                                      "ItemCode": "Burn-2289",
                                      "Description": "Red/Black Burn Band Large",
                                      "InventoryStatus": "OutOfStock"
                                  },
                                  {
                                      "ItemCode": "Burn-2296",
                                      "Description": "Red/Black Burn Band XL",
                                      "InventoryStatus": "OutOfStock"
                                  }
                                ]
                            }
                        },
                        {
                            "Description": "Shake",
                            "KitMemberItems": {
                                "KitMemberItemResponse": [
                                  {
                                      "ItemCode": "1010S",
                                      "Description": "PureCare Ballcap - Small",
                                      "InventoryStatus": "Available"
                                  },
                                  {
                                      "ItemCode": "1010M",
                                      "Description": "PureCare Ballcap - Medium",
                                      "InventoryStatus": "Available"
                                  },
                                  {
                                      "ItemCode": "1010L",
                                      "Description": "PureCare Ballcap - Large",
                                      "InventoryStatus": "Available"
                                  },
                                  {
                                      "ItemCode": "120000",
                                      "Description": "becatest",
                                      "InventoryStatus": "Available"
                                  }
                                ]
                            }
                        },
                        {
                            "Description": "Shake",
                            "KitMemberItems": {
                                "KitMemberItemResponse": [
                                  {
                                      "ItemCode": "1010S",
                                      "Description": "PureCare Ballcap - Small",
                                      "InventoryStatus": "Available"
                                  },
                                  {
                                      "ItemCode": "1010M",
                                      "Description": "PureCare Ballcap - Medium",
                                      "InventoryStatus": "Available"
                                  },
                                  {
                                      "ItemCode": "1010L",
                                      "Description": "PureCare Ballcap - Large",
                                      "InventoryStatus": "Available"
                                  },
                                  {
                                      "ItemCode": "120000",
                                      "Description": "becatest",
                                      "InventoryStatus": "Available"
                                  }
                                ]
                            }
                        }
                      ]
                  },
                  "TaxablePrice": "19.9500",
                  "ShippingPrice": "19.9500"
              },
              {
                  "ItemCode": "1002",
                  "Description": "PureCare Regenerate",
                  "Price": 19.9500,
                  "CommissionableVolume": 20,
                  "BusinessVolume": 20,
                  "Other1Price": "0.0000",
                  "Other2Price": "0.0000",
                  "Other3Price": "0.0000",
                  "Other4Price": "0.0000",
                  "Other5Price": "0.0000",
                  "Other6Price": "0.0000",
                  "Other7Price": "0.0000",
                  "Other8Price": "0.0000",
                  "Other9Price": "0.0000",
                  "Other10Price": "0.0000",
                  "Category": "Health & Wellness",
                  "CategoryID": "26",
                  "TinyPicture": "1002B.jpg",
                  "SmallPicture": "1002B.jpg",
                  "LargePicture": "1002A.jpg",
                  "ShortDetail": "Bottle of invigorating liquid",
                  "ShortDetail2": "",
                  "ShortDetail3": "",
                  "ShortDetail4": "",
                  "LongDetail": "<P><STRONG>Lorem Ipsum</STRONG> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</P>",
                  "LongDetail2": "",
                  "LongDetail3": "",
                  "LongDetail4": "",
                  "InventoryStatus": "OutOfStock",
                  "StockLevel": "-2",
                  "AvailableStockLevel": "-56",
                  "MaxAllowedOnOrder": "1",
                  "Field1": "",
                  "Field2": "",
                  "Field3": "10",
                  "Field4": "",
                  "Field5": "",
                  "Field6": "?????",
                  "Field7": "",
                  "Field8": "",
                  "Field9": "",
                  "Field10": "",
                  "OtherCheck1": "true",
                  "OtherCheck2": "false",
                  "OtherCheck3": "false",
                  "OtherCheck4": "false",
                  "OtherCheck5": "false",
                  "IsVirtual": "false",
                  "AllowOnAutoOrder": "true",
                  "IsGroupMaster": "false",
                  "GroupDescription": "",
                  "GroupMembersDescription": "",
                  "IsDynamicKitMaster": "false",
                  "TaxablePrice": "19.9000",
                  "ShippingPrice": "19.9500"
              },
              {
                  "ItemCode": "1003",
                  "Description": "PureCare Exhilerate",
                  "Price": 19.9500,
                  "CommissionableVolume": 20,
                  "BusinessVolume": 20,
                  "Other1Price": "0.0000",
                  "Other2Price": "0.0000",
                  "Other3Price": "0.0000",
                  "Other4Price": "0.0000",
                  "Other5Price": "0.0000",
                  "Other6Price": "0.0000",
                  "Other7Price": "0.0000",
                  "Other8Price": "0.0000",
                  "Other9Price": "0.0000",
                  "Other10Price": "0.0000",
                  "Category": "Health & Wellness",
                  "CategoryID": "26",
                  "TinyPicture": "1003C.jpg",
                  "SmallPicture": "1003B.jpg",
                  "LargePicture": "1003A.jpg",
                  "ShortDetail": "Bottle of invigorating liquid",
                  "ShortDetail2": "",
                  "ShortDetail3": "",
                  "ShortDetail4": "",
                  "LongDetail": "<P><STRONG>Lorem Ipsum</STRONG> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</P>",
                  "LongDetail2": "",
                  "LongDetail3": "",
                  "LongDetail4": "",
                  "InventoryStatus": "Available",
                  "StockLevel": "-1",
                  "AvailableStockLevel": "-45",
                  "MaxAllowedOnOrder": "1000000000",
                  "Field1": "",
                  "Field2": "",
                  "Field3": "",
                  "Field4": "",
                  "Field5": "",
                  "Field6": "",
                  "Field7": "",
                  "Field8": "",
                  "Field9": "",
                  "Field10": "",
                  "OtherCheck1": "false",
                  "OtherCheck2": "false",
                  "OtherCheck3": "false",
                  "OtherCheck4": "false",
                  "OtherCheck5": "false",
                  "IsVirtual": "false",
                  "AllowOnAutoOrder": "true",
                  "IsGroupMaster": "false",
                  "GroupDescription": "",
                  "GroupMembersDescription": "",
                  "IsDynamicKitMaster": "false",
                  "TaxablePrice": "19.9500",
                  "ShippingPrice": "19.9500"
              },
              {
                  "ItemCode": "1004",
                  "Description": "PureCare Celebrate",
                  "Price": 24.9500,
                  "CommissionableVolume": 25,
                  "BusinessVolume": 25,
                  "Other1Price": "0.0000",
                  "Other2Price": "0.0000",
                  "Other3Price": "0.0000",
                  "Other4Price": "0.0000",
                  "Other5Price": "0.0000",
                  "Other6Price": "0.0000",
                  "Other7Price": "0.0000",
                  "Other8Price": "0.0000",
                  "Other9Price": "0.0000",
                  "Other10Price": "0.0000",
                  "Category": "Health & Wellness",
                  "CategoryID": "26",
                  "TinyPicture": "1004C.jpg",
                  "SmallPicture": "1004B.jpg",
                  "LargePicture": "1004A.jpg",
                  "ShortDetail": "Bottle of invigorating liquid",
                  "ShortDetail2": "",
                  "ShortDetail3": "",
                  "ShortDetail4": "",
                  "LongDetail": "<P><STRONG>Lorem Ipsum</STRONG> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</P>",
                  "LongDetail2": "",
                  "LongDetail3": "",
                  "LongDetail4": "",
                  "InventoryStatus": "Available",
                  "StockLevel": "-6",
                  "AvailableStockLevel": "-98",
                  "MaxAllowedOnOrder": "1000000000",
                  "Field1": "",
                  "Field2": "",
                  "Field3": "",
                  "Field4": "",
                  "Field5": "",
                  "Field6": "",
                  "Field7": "",
                  "Field8": "",
                  "Field9": "",
                  "Field10": "",
                  "OtherCheck1": "false",
                  "OtherCheck2": "true",
                  "OtherCheck3": "false",
                  "OtherCheck4": "false",
                  "OtherCheck5": "false",
                  "IsVirtual": "false",
                  "AllowOnAutoOrder": "true",
                  "IsGroupMaster": "false",
                  "GroupDescription": "",
                  "GroupMembersDescription": "",
                  "IsDynamicKitMaster": "false",
                  "TaxablePrice": "24.9500",
                  "ShippingPrice": "24.9500"
              },
              {
                  "ItemCode": "1005",
                  "Description": "PureCare Invigorate (6-pack)",
                  "Price": 109.9500,
                  "CommissionableVolume": 110,
                  "BusinessVolume": 110,
                  "Other1Price": "0.0000",
                  "Other2Price": "0.0000",
                  "Other3Price": "0.0000",
                  "Other4Price": "0.0000",
                  "Other5Price": "0.0000",
                  "Other6Price": "0.0000",
                  "Other7Price": "0.0000",
                  "Other8Price": "0.0000",
                  "Other9Price": "0.0000",
                  "Other10Price": "0.0000",
                  "Category": "Health & Wellness",
                  "CategoryID": "26",
                  "TinyPicture": "1005C.jpg",
                  "SmallPicture": "1005B.jpg",
                  "LargePicture": "1005A.jpg",
                  "ShortDetail": "Bottle of 6 invigorating liquid",
                  "ShortDetail2": "",
                  "ShortDetail3": "",
                  "ShortDetail4": "",
                  "LongDetail": "<P><STRONG>Lorem Ipsum</STRONG> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</P>",
                  "LongDetail2": "",
                  "LongDetail3": "",
                  "LongDetail4": "",
                  "InventoryStatus": "Available",
                  "StockLevel": "0",
                  "AvailableStockLevel": "-16",
                  "MaxAllowedOnOrder": "1000000000",
                  "Field1": "",
                  "Field2": "",
                  "Field3": "",
                  "Field4": "",
                  "Field5": "",
                  "Field6": "",
                  "Field7": "",
                  "Field8": "",
                  "Field9": "",
                  "Field10": "",
                  "OtherCheck1": "false",
                  "OtherCheck2": "false",
                  "OtherCheck3": "false",
                  "OtherCheck4": "false",
                  "OtherCheck5": "false",
                  "IsVirtual": "false",
                  "AllowOnAutoOrder": "true",
                  "IsGroupMaster": "false",
                  "GroupDescription": "",
                  "GroupMembersDescription": "",
                  "IsDynamicKitMaster": "false",
                  "TaxablePrice": "109.9500",
                  "ShippingPrice": "109.9500"
              },
              {
                  "ItemCode": "1007",
                  "Description": "PureCare Xperience Facial Spray",
                  "Price": 14.9500,
                  "CommissionableVolume": 15,
                  "BusinessVolume": 15,
                  "Other1Price": "0.0000",
                  "Other2Price": "0.0000",
                  "Other3Price": "0.0000",
                  "Other4Price": "0.0000",
                  "Other5Price": "0.0000",
                  "Other6Price": "0.0000",
                  "Other7Price": "0.0000",
                  "Other8Price": "0.0000",
                  "Other9Price": "0.0000",
                  "Other10Price": "0.0000",
                  "Category": "Health & Wellness",
                  "CategoryID": "26",
                  "TinyPicture": "1007C.jpg",
                  "SmallPicture": "1007B.jpg",
                  "LargePicture": "1007A.jpg",
                  "ShortDetail": "Bottle of invigorating facial spray",
                  "ShortDetail2": "",
                  "ShortDetail3": "",
                  "ShortDetail4": "",
                  "LongDetail": "<P><STRONG>Lorem Ipsum</STRONG> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</P>",
                  "LongDetail2": "",
                  "LongDetail3": "",
                  "LongDetail4": "",
                  "InventoryStatus": "Available",
                  "StockLevel": "0",
                  "AvailableStockLevel": "-4",
                  "MaxAllowedOnOrder": "1000000000",
                  "Field1": "",
                  "Field2": "",
                  "Field3": "",
                  "Field4": "",
                  "Field5": "",
                  "Field6": "",
                  "Field7": "",
                  "Field8": "",
                  "Field9": "",
                  "Field10": "",
                  "OtherCheck1": "false",
                  "OtherCheck2": "false",
                  "OtherCheck3": "false",
                  "OtherCheck4": "false",
                  "OtherCheck5": "false",
                  "IsVirtual": "false",
                  "AllowOnAutoOrder": "true",
                  "IsGroupMaster": "false",
                  "GroupDescription": "",
                  "GroupMembersDescription": "",
                  "IsDynamicKitMaster": "false",
                  "TaxablePrice": "14.9500",
                  "ShippingPrice": "14.9500"
              },
              {
                  "ItemCode": "1008",
                  "Description": "PureCare Xtended",
                  "Price": 24.9500,
                  "CommissionableVolume": 25,
                  "BusinessVolume": 25,
                  "Other1Price": "1.0000",
                  "Other2Price": "0.0000",
                  "Other3Price": "0.0000",
                  "Other4Price": "0.0000",
                  "Other5Price": "0.0000",
                  "Other6Price": "0.0000",
                  "Other7Price": "0.0000",
                  "Other8Price": "0.0000",
                  "Other9Price": "0.0000",
                  "Other10Price": "0.0000",
                  "Category": "Health & Wellness",
                  "CategoryID": "26",
                  "TinyPicture": "1008C.jpg",
                  "SmallPicture": "1008B.jpg",
                  "LargePicture": "1008A.jpg",
                  "ShortDetail": "Bottle of invigorating liquid",
                  "ShortDetail2": "",
                  "ShortDetail3": "",
                  "ShortDetail4": "",
                  "LongDetail": "<P><STRONG>Lorem Ipsum</STRONG> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</P>",
                  "LongDetail2": "",
                  "LongDetail3": "",
                  "LongDetail4": "",
                  "InventoryStatus": "Available",
                  "StockLevel": "0",
                  "AvailableStockLevel": "-6",
                  "MaxAllowedOnOrder": "1000000000",
                  "Field1": "",
                  "Field2": "",
                  "Field3": "",
                  "Field4": "",
                  "Field5": "",
                  "Field6": "",
                  "Field7": "",
                  "Field8": "",
                  "Field9": "",
                  "Field10": "",
                  "OtherCheck1": "false",
                  "OtherCheck2": "false",
                  "OtherCheck3": "false",
                  "OtherCheck4": "false",
                  "OtherCheck5": "false",
                  "IsVirtual": "false",
                  "AllowOnAutoOrder": "true",
                  "IsGroupMaster": "false",
                  "GroupDescription": "",
                  "GroupMembersDescription": "",
                  "IsDynamicKitMaster": "false",
                  "TaxablePrice": "24.9500",
                  "ShippingPrice": "24.9500"
              },
              {
                  "ItemCode": "1014",
                  "Description": "PureCare Distributor Training Kit",
                  "Price": 249.9900,
                  "CommissionableVolume": 250,
                  "BusinessVolume": 250,
                  "Other1Price": "0.0000",
                  "Other2Price": "0.0000",
                  "Other3Price": "0.0000",
                  "Other4Price": "0.0000",
                  "Other5Price": "0.0000",
                  "Other6Price": "0.0000",
                  "Other7Price": "0.0000",
                  "Other8Price": "0.0000",
                  "Other9Price": "0.0000",
                  "Other10Price": "0.0000",
                  "Category": "Marketing",
                  "CategoryID": "27",
                  "TinyPicture": "1014C.jpg",
                  "SmallPicture": "1014B.jpg",
                  "LargePicture": "1014A.jpg",
                  "ShortDetail": "training kit",
                  "ShortDetail2": "",
                  "ShortDetail3": "",
                  "ShortDetail4": "",
                  "LongDetail": "<P><STRONG>Lorem Ipsum</STRONG> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</P>",
                  "LongDetail2": "",
                  "LongDetail3": "",
                  "LongDetail4": "",
                  "InventoryStatus": "Available",
                  "StockLevel": "0",
                  "AvailableStockLevel": "-5",
                  "MaxAllowedOnOrder": "1000000000",
                  "Field1": "",
                  "Field2": "",
                  "Field3": "",
                  "Field4": "",
                  "Field5": "",
                  "Field6": "",
                  "Field7": "",
                  "Field8": "",
                  "Field9": "",
                  "Field10": "",
                  "OtherCheck1": "false",
                  "OtherCheck2": "false",
                  "OtherCheck3": "false",
                  "OtherCheck4": "false",
                  "OtherCheck5": "false",
                  "IsVirtual": "false",
                  "AllowOnAutoOrder": "true",
                  "IsGroupMaster": "false",
                  "GroupDescription": "",
                  "GroupMembersDescription": "",
                  "IsDynamicKitMaster": "false",
                  "TaxablePrice": "249.9900",
                  "ShippingPrice": "249.9900"
              },
              {
                  "ItemCode": "1013",
                  "Description": "PureCare Training DVD",
                  "Price": 14.9500,
                  "CommissionableVolume": 15,
                  "BusinessVolume": 15,
                  "Other1Price": "0.0000",
                  "Other2Price": "0.0000",
                  "Other3Price": "0.0000",
                  "Other4Price": "0.0000",
                  "Other5Price": "0.0000",
                  "Other6Price": "0.0000",
                  "Other7Price": "0.0000",
                  "Other8Price": "0.0000",
                  "Other9Price": "0.0000",
                  "Other10Price": "0.0000",
                  "Category": "Marketing",
                  "CategoryID": "27",
                  "TinyPicture": "1013C.jpg",
                  "SmallPicture": "1013B.jpg",
                  "LargePicture": "1013A.jpg",
                  "ShortDetail": "training CD",
                  "ShortDetail2": "",
                  "ShortDetail3": "",
                  "ShortDetail4": "",
                  "LongDetail": "<P><STRONG>Lorem Ipsum</STRONG> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</P>",
                  "LongDetail2": "",
                  "LongDetail3": "",
                  "LongDetail4": "",
                  "InventoryStatus": "Available",
                  "StockLevel": "0",
                  "AvailableStockLevel": "-1",
                  "MaxAllowedOnOrder": "1000000000",
                  "Field1": "",
                  "Field2": "",
                  "Field3": "",
                  "Field4": "",
                  "Field5": "",
                  "Field6": "",
                  "Field7": "",
                  "Field8": "",
                  "Field9": "",
                  "Field10": "",
                  "OtherCheck1": "false",
                  "OtherCheck2": "false",
                  "OtherCheck3": "false",
                  "OtherCheck4": "false",
                  "OtherCheck5": "false",
                  "IsVirtual": "false",
                  "AllowOnAutoOrder": "true",
                  "IsGroupMaster": "false",
                  "GroupDescription": "",
                  "GroupMembersDescription": "",
                  "IsDynamicKitMaster": "false",
                  "TaxablePrice": "14.9500",
                  "ShippingPrice": "14.9500"
              },
              {
                  "ItemCode": "1010",
                  "Description": "PureCare Ballcap",
                  "Price": 14.9500,
                  "CommissionableVolume": 15,
                  "BusinessVolume": 15,
                  "Other1Price": "0.0000",
                  "Other2Price": "0.0000",
                  "Other3Price": "0.0000",
                  "Other4Price": "0.0000",
                  "Other5Price": "0.0000",
                  "Other6Price": "0.0000",
                  "Other7Price": "0.0000",
                  "Other8Price": "0.0000",
                  "Other9Price": "0.0000",
                  "Other10Price": "0.0000",
                  "Category": "Marketing",
                  "CategoryID": "27",
                  "TinyPicture": "1010C.jpg",
                  "SmallPicture": "1010B.jpg",
                  "LargePicture": "1010A.jpg",
                  "ShortDetail": "PureCare Ballcap",
                  "ShortDetail2": "",
                  "ShortDetail3": "",
                  "ShortDetail4": "",
                  "LongDetail": "<P><STRONG>Lorem Ipsum</STRONG> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</P>",
                  "LongDetail2": "",
                  "LongDetail3": "",
                  "LongDetail4": "",
                  "InventoryStatus": "Available",
                  "StockLevel": "0",
                  "AvailableStockLevel": "-2",
                  "MaxAllowedOnOrder": "1000000000",
                  "Field1": "",
                  "Field2": "",
                  "Field3": "",
                  "Field4": "",
                  "Field5": "",
                  "Field6": "",
                  "Field7": "",
                  "Field8": "",
                  "Field9": "",
                  "Field10": "",
                  "OtherCheck1": "false",
                  "OtherCheck2": "false",
                  "OtherCheck3": "false",
                  "OtherCheck4": "false",
                  "OtherCheck5": "false",
                  "IsVirtual": "false",
                  "AllowOnAutoOrder": "true",
                  "IsGroupMaster": "true",
                  "GroupDescription": "PureCare Ballcap",
                  "GroupMembersDescription": "Size",
                  "GroupMembers": {
                      "ItemMemberResponse": [
                        {
                            "ItemCode": "1010S",
                            "MemberDescription": "Small",
                            "ItemDescription": "PureCare Ballcap - Small",
                            "InventoryStatus": "Available"
                        },
                        {
                            "ItemCode": "1010M",
                            "MemberDescription": "Medium",
                            "ItemDescription": "PureCare Ballcap - Medium",
                            "InventoryStatus": "Available"
                        },
                        {
                            "ItemCode": "1010L",
                            "MemberDescription": "Large",
                            "ItemDescription": "PureCare Ballcap - Large",
                            "InventoryStatus": "Available"
                        }
                      ]
                  },
                  "IsDynamicKitMaster": "false",
                  "TaxablePrice": "14.9500",
                  "ShippingPrice": "14.9500"
              },
              {
                  "ItemCode": "1011",
                  "Description": "PureCare Bottle Opener",
                  "Price": 9.9500,
                  "CommissionableVolume": 10,
                  "BusinessVolume": 10,
                  "Other1Price": "0.0000",
                  "Other2Price": "0.0000",
                  "Other3Price": "0.0000",
                  "Other4Price": "0.0000",
                  "Other5Price": "0.0000",
                  "Other6Price": "0.0000",
                  "Other7Price": "0.0000",
                  "Other8Price": "0.0000",
                  "Other9Price": "0.0000",
                  "Other10Price": "0.0000",
                  "Category": "Marketing",
                  "CategoryID": "27",
                  "TinyPicture": "1011C.jpg",
                  "SmallPicture": "1011B.jpg",
                  "LargePicture": "1011A.jpg",
                  "ShortDetail": "bottle opener",
                  "ShortDetail2": "",
                  "ShortDetail3": "",
                  "ShortDetail4": "",
                  "LongDetail": "<P><STRONG>Lorem Ipsum</STRONG> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</P>",
                  "LongDetail2": "",
                  "LongDetail3": "",
                  "LongDetail4": "",
                  "InventoryStatus": "Available",
                  "StockLevel": "0",
                  "AvailableStockLevel": "-3",
                  "MaxAllowedOnOrder": "1000000000",
                  "Field1": "",
                  "Field2": "",
                  "Field3": "",
                  "Field4": "",
                  "Field5": "",
                  "Field6": "",
                  "Field7": "",
                  "Field8": "",
                  "Field9": "",
                  "Field10": "",
                  "OtherCheck1": "false",
                  "OtherCheck2": "false",
                  "OtherCheck3": "false",
                  "OtherCheck4": "false",
                  "OtherCheck5": "false",
                  "IsVirtual": "false",
                  "AllowOnAutoOrder": "true",
                  "IsGroupMaster": "false",
                  "GroupDescription": "",
                  "GroupMembersDescription": "",
                  "IsDynamicKitMaster": "false",
                  "TaxablePrice": "9.9500",
                  "ShippingPrice": "9.9500"
              },
              {
                  "ItemCode": "1012",
                  "Description": "PureCare Pocket Knife",
                  "Price": 14.9500,
                  "CommissionableVolume": 15,
                  "BusinessVolume": 15,
                  "Other1Price": "0.0000",
                  "Other2Price": "0.0000",
                  "Other3Price": "0.0000",
                  "Other4Price": "0.0000",
                  "Other5Price": "0.0000",
                  "Other6Price": "0.0000",
                  "Other7Price": "0.0000",
                  "Other8Price": "0.0000",
                  "Other9Price": "0.0000",
                  "Other10Price": "0.0000",
                  "Category": "Marketing",
                  "CategoryID": "27",
                  "TinyPicture": "1012C.jpg",
                  "SmallPicture": "1012B.jpg",
                  "LargePicture": "1012A.jpg",
                  "ShortDetail": "pocket knife",
                  "ShortDetail2": "",
                  "ShortDetail3": "",
                  "ShortDetail4": "",
                  "LongDetail": "<P><STRONG>Lorem Ipsum</STRONG> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</P>",
                  "LongDetail2": "",
                  "LongDetail3": "",
                  "LongDetail4": "",
                  "InventoryStatus": "Available",
                  "StockLevel": "-1",
                  "AvailableStockLevel": "-1",
                  "MaxAllowedOnOrder": "1000000000",
                  "Field1": "",
                  "Field2": "",
                  "Field3": "",
                  "Field4": "",
                  "Field5": "",
                  "Field6": "",
                  "Field7": "",
                  "Field8": "",
                  "Field9": "",
                  "Field10": "",
                  "OtherCheck1": "false",
                  "OtherCheck2": "false",
                  "OtherCheck3": "false",
                  "OtherCheck4": "false",
                  "OtherCheck5": "false",
                  "IsVirtual": "false",
                  "AllowOnAutoOrder": "true",
                  "IsGroupMaster": "false",
                  "GroupDescription": "",
                  "GroupMembersDescription": "",
                  "IsDynamicKitMaster": "false",
                  "TaxablePrice": "14.9500",
                  "ShippingPrice": "14.9500"
              },
              {
                  "ItemCode": "1009",
                  "Description": "PureCare Success Guide",
                  "Price": 49.9500,
                  "CommissionableVolume": 50,
                  "BusinessVolume": 50,
                  "Other1Price": "0.0000",
                  "Other2Price": "0.0000",
                  "Other3Price": "0.0000",
                  "Other4Price": "0.0000",
                  "Other5Price": "0.0000",
                  "Other6Price": "0.0000",
                  "Other7Price": "0.0000",
                  "Other8Price": "0.0000",
                  "Other9Price": "0.0000",
                  "Other10Price": "0.0000",
                  "Category": "Marketing",
                  "CategoryID": "27",
                  "TinyPicture": "1009C.jpg",
                  "SmallPicture": "1009B.jpg",
                  "LargePicture": "1009A.jpg",
                  "ShortDetail": "success guide",
                  "ShortDetail2": "",
                  "ShortDetail3": "",
                  "ShortDetail4": "",
                  "LongDetail": "<P><STRONG>Lorem Ipsum</STRONG> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</P>",
                  "LongDetail2": "",
                  "LongDetail3": "",
                  "LongDetail4": "",
                  "InventoryStatus": "Available",
                  "StockLevel": "0",
                  "AvailableStockLevel": "-4",
                  "MaxAllowedOnOrder": "1000000000",
                  "Field1": "",
                  "Field2": "",
                  "Field3": "",
                  "Field4": "",
                  "Field5": "",
                  "Field6": "",
                  "Field7": "",
                  "Field8": "",
                  "Field9": "",
                  "Field10": "",
                  "OtherCheck1": "false",
                  "OtherCheck2": "false",
                  "OtherCheck3": "false",
                  "OtherCheck4": "false",
                  "OtherCheck5": "false",
                  "IsVirtual": "false",
                  "AllowOnAutoOrder": "true",
                  "IsGroupMaster": "false",
                  "GroupDescription": "",
                  "GroupMembersDescription": "",
                  "IsDynamicKitMaster": "false",
                  "TaxablePrice": "49.9500",
                  "ShippingPrice": "49.9500"
              }
            ]
        }
    };

    return {
        get: function () {
            return _items.Items.ItemResponse;
        }
    };
});